package vista;

import conexion.Fachada;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ProductosVenta;
import modelo.ProductosVentaDAO;
import modelo.Vendedor;
import modelo.VendedorDao;
import modelo.Venta;
import modelo.VentaDao;

public class MarcoVenta extends javax.swing.JFrame {
    ArrayList precios;
    public MarcoVenta() {
        precios = new ArrayList();
        //setSize(300,400);
        initComponents();
        super.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        agregarElementosCombo();
        agregarButton.addActionListener(new ManejoEventos());
        btnNuevaVenta.addActionListener(new ManejoEventos());
        btnRegresar.addActionListener(new ManejoEventos());
        
        
    }

    public void agregarDatos(String nombrePoducto,int indexProducto){
        try{
            
            Connection connection = Fachada.getConnection();
            //for (int i = 0; i < miListaVentas.size(); i++) {
            
                String sql = "update venta set total_ventas = total_ventas + "
                        +precios.get(indexProducto)+" where vendedor_id= '123'";
                
                
                PreparedStatement preparedStatement = connection.prepareStatement(sql);
                preparedStatement.executeUpdate(sql);
                
                
                String sqlAlter = "update productosVenta set cantidad = cantidad - "
                        +1+" where nombreProducto = '"+nombrePoducto+"'";
                
                PreparedStatement pstm = connection.prepareStatement(sqlAlter);                
                pstm.executeUpdate(sqlAlter);
                
          
            
        }catch(Exception e){
           e.printStackTrace();
            
        }
    }
    
    public void agregarElementosCombo(){
        
         //ArrayList precios = new ArrayList();
        
         Connection connection = Fachada.getConnection();
         try{
             
             String sql = "select * from productosVenta";
             PreparedStatement pstm = connection.prepareStatement(sql);
             ResultSet rs = pstm.executeQuery();
             while(rs.next()){
                 productosComboBox.addItem(rs.getString(3));
                 precios.add(rs.getInt(5));
             }
             
         }catch(Exception e){
             e.printStackTrace();
         }
    }
    
    public class ManejoEventos implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            if(e.getSource() == agregarButton){
              /* String datosRow = {
                   
               } */
               String nombre = ""+productosComboBox.getSelectedItem();
               int index = productosComboBox.getSelectedIndex();
               areaListaProductos.append(""
                       +productosComboBox.getSelectedItem()+"\n");
               agregarDatos(nombre,index);               
            }else if (e.getSource() == btnNuevaVenta){
                areaListaProductos.setText("");
            }else if(e.getSource() == btnRegresar){
                dispose();
            }
        }
        
    }
    
    //public void regresar

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        productosComboBox = new javax.swing.JComboBox<>();
        agregarButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaListaProductos = new javax.swing.JTextArea();
        btnNuevaVenta = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Producto:");

        productosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productosComboBoxActionPerformed(evt);
            }
        });

        agregarButton.setText("Agregar");
        agregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarButtonActionPerformed(evt);
            }
        });

        areaListaProductos.setColumns(20);
        areaListaProductos.setRows(5);
        jScrollPane2.setViewportView(areaListaProductos);

        btnNuevaVenta.setText("Nueva Venta");
        btnNuevaVenta.setActionCommand("Nueva Venta");
        btnNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaVentaActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(agregarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNuevaVenta))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(271, Short.MAX_VALUE)
                        .addComponent(btnRegresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(productosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarButton)
                    .addComponent(btnNuevaVenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButtonActionPerformed
        
    }//GEN-LAST:event_agregarButtonActionPerformed

    private void productosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productosComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productosComboBoxActionPerformed

    private void btnNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarcoVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarcoVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarcoVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarcoVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                //new MarcoVenta().setVisible(true);
                MarcoVenta miMarco = new MarcoVenta();
                miMarco.setVisible(false);
                miMarco.setLocationRelativeTo(null);
                miMarco.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarButton;
    private javax.swing.JTextArea areaListaProductos;
    private javax.swing.JButton btnNuevaVenta;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> productosComboBox;
    // End of variables declaration//GEN-END:variables
}
